version: '3.1'
services:
  app:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/etc/nginx/html
  mongodb:
    image: mongo
    volumes:
      -./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: 
  spring:
    image: hesuanjiancedian:0.0.1
    command: "--spring.profiles.active=prod"
    depends_on:
      - mongodb
    expose:
      - 8080
